CREATE TABLE PROD_REGION (
  R_REGIONKEY     INTEGER        NOT NULL,
  R_NAME          CHAR(25)       NOT NULL,
  R_COMMENT       VARCHAR(152)   NOT NULL
);

CREATE TABLE PROD_NATION (
  N_NATIONKEY     INTEGER        NOT NULL,
  N_NAME          CHAR(25)       NOT NULL,
  N_REGIONKEY     INTEGER        NOT NULL,
  N_COMMENT       VARCHAR(152)   NOT NULL
);

CREATE TABLE PROD_CUSTOMER (
  C_CUSTKEY       INTEGER        NOT NULL,
  C_NAME          VARCHAR(25)    NOT NULL,
  C_ADDRESS       VARCHAR(40)    NOT NULL,
  C_NATIONKEY     INTEGER        NOT NULL,
  C_PHONE         CHAR(15)       NOT NULL,
  C_ACCTBAL       DOUBLE         NOT NULL,
  C_MKTSEGMENT    CHAR(10)       NOT NULL,
  C_COMMENT       VARCHAR(117)   NOT NULL
);

CREATE TABLE PROD_RATES (
  RS_TIMESTAMP    TIMESTAMP(3)   NOT NULL,
  RS_SYMBOL       CHAR(3)        NOT NULL,
  RS_RATE         DOUBLE         NOT NULL
);